namespace MicroDev.Core.Simulation;

public enum EfficiencyUpgradeType
{
    MechanicalKeyboard = 0,
    SnippetLibrary,
    LintBot,
    PomodoroTimer,
    NoiseCancelingHeadphones,
    InterviewNotebook,
    AutoFormatter,
    MacroPad,
    DeskPlant,
    MealPrepContainers,
    CourierPrime,
    BugTriageBoard,
    FocusLamp,
    HydrationHabit,
    DualMonitorArm,
    SearchIndexer,
    TestHarnessSandbox,
    SnapshotSuite,
    PreCommitHooks,
    ReviewChecklist,
    StandingDeskMat,
    ErgonomicChair,
    LoFiPlaylist,
    WindowAirConditioner,
    TeaThermos,
    BlueLightGlasses,
    InterviewFlashCards,
    OfferSpreadsheet,
    GroceryStaples,
    RiceCooker,
    DeliveryFavorites,
    LunchCalendar,
    IncidentRunbook,
    SentryDashboard,
}
