<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-ios</TargetFramework>
    <SupportedOSPlatformVersion>11.2</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <IsTrimmable>true</IsTrimmable>
    <TrimMode>partial</TrimMode>
    <DefineConstants>$(DefineConstants);IOS</DefineConstants>
    <KniPlatform>iOS</KniPlatform>
    <ApplicationId>$(MicroDevIosBundleId)</ApplicationId>
    <ApplicationVersion>$(MicroDevIosBuildNumber)</ApplicationVersion>
    <ApplicationDisplayVersion>$(Version)</ApplicationDisplayVersion>
    <CodesignKey>iPhone Developer</CodesignKey>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="nkast.Kni.Platform.iOS.GL" Version="$(KniMobilePlatformVersion)" />
    <PackageReference Include="nkast.Xna.Framework.Content.Pipeline.Builder" Version="$(KniVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MicroDev.Core\MicroDev.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Info.plist" />
    <None Include="Entitlements.plist" />
  </ItemGroup>

  <ItemGroup>
    <KniContentReference Include="Content\Content.mgcb" />
  </ItemGroup>
</Project>
